[project]
name = "mcp-betfair"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "logfire[fastapi,sqlite3]>=3.19.0",
    "mem0ai>=0.1.114",
    "pydantic-ai>=0.2.18",
]
